// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ComposeRetweet.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::TwitterMicroservices;

class ComposeRetweetHandler : virtual public ComposeRetweetIf {
 public:
  ComposeRetweetHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void upload(const std::string& req_id, const std::string& type, const std::string& data) {
    // Your implementation goes here
    printf("upload\n");
  }

  void upload_tweet(const Tweet& tweet, const std::string& req_id) {
    // Your implementation goes here
    printf("upload_tweet\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ComposeRetweetHandler> handler(new ComposeRetweetHandler());
  shared_ptr<TProcessor> processor(new ComposeRetweetProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

