/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GetRating_H
#define GetRating_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "NetflixMicroservices_types.h"

namespace NetflixMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GetRatingIf {
 public:
  virtual ~GetRatingIf() {}
  virtual void ping() = 0;
  virtual void get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no) = 0;
};

class GetRatingIfFactory {
 public:
  typedef GetRatingIf Handler;

  virtual ~GetRatingIfFactory() {}

  virtual GetRatingIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GetRatingIf* /* handler */) = 0;
};

class GetRatingIfSingletonFactory : virtual public GetRatingIfFactory {
 public:
  GetRatingIfSingletonFactory(const boost::shared_ptr<GetRatingIf>& iface) : iface_(iface) {}
  virtual ~GetRatingIfSingletonFactory() {}

  virtual GetRatingIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(GetRatingIf* /* handler */) {}

 protected:
  boost::shared_ptr<GetRatingIf> iface_;
};

class GetRatingNull : virtual public GetRatingIf {
 public:
  virtual ~GetRatingNull() {}
  void ping() {
    return;
  }
  void get_rating(const std::string& /* req_id */, const std::string& /* movie_id */, const int32_t /* server_no */) {
    return;
  }
};


class GetRating_ping_args {
 public:

  GetRating_ping_args(const GetRating_ping_args&);
  GetRating_ping_args& operator=(const GetRating_ping_args&);
  GetRating_ping_args() {
  }

  virtual ~GetRating_ping_args() throw();

  bool operator == (const GetRating_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const GetRating_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetRating_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetRating_ping_pargs {
 public:


  virtual ~GetRating_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetRating_ping_result {
 public:

  GetRating_ping_result(const GetRating_ping_result&);
  GetRating_ping_result& operator=(const GetRating_ping_result&);
  GetRating_ping_result() {
  }

  virtual ~GetRating_ping_result() throw();

  bool operator == (const GetRating_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const GetRating_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetRating_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetRating_ping_presult {
 public:


  virtual ~GetRating_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _GetRating_get_rating_args__isset {
  _GetRating_get_rating_args__isset() : req_id(false), movie_id(false), server_no(false) {}
  bool req_id :1;
  bool movie_id :1;
  bool server_no :1;
} _GetRating_get_rating_args__isset;

class GetRating_get_rating_args {
 public:

  GetRating_get_rating_args(const GetRating_get_rating_args&);
  GetRating_get_rating_args& operator=(const GetRating_get_rating_args&);
  GetRating_get_rating_args() : req_id(), movie_id(), server_no(0) {
  }

  virtual ~GetRating_get_rating_args() throw();
  std::string req_id;
  std::string movie_id;
  int32_t server_no;

  _GetRating_get_rating_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_movie_id(const std::string& val);

  void __set_server_no(const int32_t val);

  bool operator == (const GetRating_get_rating_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(movie_id == rhs.movie_id))
      return false;
    if (!(server_no == rhs.server_no))
      return false;
    return true;
  }
  bool operator != (const GetRating_get_rating_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetRating_get_rating_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetRating_get_rating_pargs {
 public:


  virtual ~GetRating_get_rating_pargs() throw();
  const std::string* req_id;
  const std::string* movie_id;
  const int32_t* server_no;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class GetRatingClient : virtual public GetRatingIf {
 public:
  GetRatingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GetRatingClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no);
  void send_get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GetRatingProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<GetRatingIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (GetRatingProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_rating(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GetRatingProcessor(boost::shared_ptr<GetRatingIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &GetRatingProcessor::process_ping;
    processMap_["get_rating"] = &GetRatingProcessor::process_get_rating;
  }

  virtual ~GetRatingProcessor() {}
};

class GetRatingProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GetRatingProcessorFactory(const ::boost::shared_ptr< GetRatingIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< GetRatingIfFactory > handlerFactory_;
};

class GetRatingMultiface : virtual public GetRatingIf {
 public:
  GetRatingMultiface(std::vector<boost::shared_ptr<GetRatingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GetRatingMultiface() {}
 protected:
  std::vector<boost::shared_ptr<GetRatingIf> > ifaces_;
  GetRatingMultiface() {}
  void add(boost::shared_ptr<GetRatingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_rating(req_id, movie_id, server_no);
    }
    ifaces_[i]->get_rating(req_id, movie_id, server_no);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GetRatingConcurrentClient : virtual public GetRatingIf {
 public:
  GetRatingConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GetRatingConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no);
  void send_get_rating(const std::string& req_id, const std::string& movie_id, const int32_t server_no);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
