/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef GetThumbnail_H
#define GetThumbnail_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "NetflixMicroservices_types.h"

namespace NetflixMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class GetThumbnailIf {
 public:
  virtual ~GetThumbnailIf() {}
  virtual void ping() = 0;
  virtual void get_thumbnail(const std::string& req_id, const std::string& movie_id) = 0;
};

class GetThumbnailIfFactory {
 public:
  typedef GetThumbnailIf Handler;

  virtual ~GetThumbnailIfFactory() {}

  virtual GetThumbnailIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(GetThumbnailIf* /* handler */) = 0;
};

class GetThumbnailIfSingletonFactory : virtual public GetThumbnailIfFactory {
 public:
  GetThumbnailIfSingletonFactory(const boost::shared_ptr<GetThumbnailIf>& iface) : iface_(iface) {}
  virtual ~GetThumbnailIfSingletonFactory() {}

  virtual GetThumbnailIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(GetThumbnailIf* /* handler */) {}

 protected:
  boost::shared_ptr<GetThumbnailIf> iface_;
};

class GetThumbnailNull : virtual public GetThumbnailIf {
 public:
  virtual ~GetThumbnailNull() {}
  void ping() {
    return;
  }
  void get_thumbnail(const std::string& /* req_id */, const std::string& /* movie_id */) {
    return;
  }
};


class GetThumbnail_ping_args {
 public:

  GetThumbnail_ping_args(const GetThumbnail_ping_args&);
  GetThumbnail_ping_args& operator=(const GetThumbnail_ping_args&);
  GetThumbnail_ping_args() {
  }

  virtual ~GetThumbnail_ping_args() throw();

  bool operator == (const GetThumbnail_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const GetThumbnail_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetThumbnail_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetThumbnail_ping_pargs {
 public:


  virtual ~GetThumbnail_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetThumbnail_ping_result {
 public:

  GetThumbnail_ping_result(const GetThumbnail_ping_result&);
  GetThumbnail_ping_result& operator=(const GetThumbnail_ping_result&);
  GetThumbnail_ping_result() {
  }

  virtual ~GetThumbnail_ping_result() throw();

  bool operator == (const GetThumbnail_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const GetThumbnail_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetThumbnail_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetThumbnail_ping_presult {
 public:


  virtual ~GetThumbnail_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _GetThumbnail_get_thumbnail_args__isset {
  _GetThumbnail_get_thumbnail_args__isset() : req_id(false), movie_id(false) {}
  bool req_id :1;
  bool movie_id :1;
} _GetThumbnail_get_thumbnail_args__isset;

class GetThumbnail_get_thumbnail_args {
 public:

  GetThumbnail_get_thumbnail_args(const GetThumbnail_get_thumbnail_args&);
  GetThumbnail_get_thumbnail_args& operator=(const GetThumbnail_get_thumbnail_args&);
  GetThumbnail_get_thumbnail_args() : req_id(), movie_id() {
  }

  virtual ~GetThumbnail_get_thumbnail_args() throw();
  std::string req_id;
  std::string movie_id;

  _GetThumbnail_get_thumbnail_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_movie_id(const std::string& val);

  bool operator == (const GetThumbnail_get_thumbnail_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(movie_id == rhs.movie_id))
      return false;
    return true;
  }
  bool operator != (const GetThumbnail_get_thumbnail_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const GetThumbnail_get_thumbnail_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class GetThumbnail_get_thumbnail_pargs {
 public:


  virtual ~GetThumbnail_get_thumbnail_pargs() throw();
  const std::string* req_id;
  const std::string* movie_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class GetThumbnailClient : virtual public GetThumbnailIf {
 public:
  GetThumbnailClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GetThumbnailClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void get_thumbnail(const std::string& req_id, const std::string& movie_id);
  void send_get_thumbnail(const std::string& req_id, const std::string& movie_id);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class GetThumbnailProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<GetThumbnailIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (GetThumbnailProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_thumbnail(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  GetThumbnailProcessor(boost::shared_ptr<GetThumbnailIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &GetThumbnailProcessor::process_ping;
    processMap_["get_thumbnail"] = &GetThumbnailProcessor::process_get_thumbnail;
  }

  virtual ~GetThumbnailProcessor() {}
};

class GetThumbnailProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  GetThumbnailProcessorFactory(const ::boost::shared_ptr< GetThumbnailIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< GetThumbnailIfFactory > handlerFactory_;
};

class GetThumbnailMultiface : virtual public GetThumbnailIf {
 public:
  GetThumbnailMultiface(std::vector<boost::shared_ptr<GetThumbnailIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~GetThumbnailMultiface() {}
 protected:
  std::vector<boost::shared_ptr<GetThumbnailIf> > ifaces_;
  GetThumbnailMultiface() {}
  void add(boost::shared_ptr<GetThumbnailIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void get_thumbnail(const std::string& req_id, const std::string& movie_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_thumbnail(req_id, movie_id);
    }
    ifaces_[i]->get_thumbnail(req_id, movie_id);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class GetThumbnailConcurrentClient : virtual public GetThumbnailIf {
 public:
  GetThumbnailConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  GetThumbnailConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void get_thumbnail(const std::string& req_id, const std::string& movie_id);
  void send_get_thumbnail(const std::string& req_id, const std::string& movie_id);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
