/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MongoTweetStorage_H
#define MongoTweetStorage_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "TwitterMicroservices_types.h"

namespace TwitterMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MongoTweetStorageIf {
 public:
  virtual ~MongoTweetStorageIf() {}
  virtual void ping() = 0;
  virtual void store_tweet(const Tweet& tweet, const std::string& req_id) = 0;
  virtual void get_tweet(std::string& _return, const std::string& user_id, const std::string& unique_id, const std::string& req_id) = 0;
};

class MongoTweetStorageIfFactory {
 public:
  typedef MongoTweetStorageIf Handler;

  virtual ~MongoTweetStorageIfFactory() {}

  virtual MongoTweetStorageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MongoTweetStorageIf* /* handler */) = 0;
};

class MongoTweetStorageIfSingletonFactory : virtual public MongoTweetStorageIfFactory {
 public:
  MongoTweetStorageIfSingletonFactory(const boost::shared_ptr<MongoTweetStorageIf>& iface) : iface_(iface) {}
  virtual ~MongoTweetStorageIfSingletonFactory() {}

  virtual MongoTweetStorageIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MongoTweetStorageIf* /* handler */) {}

 protected:
  boost::shared_ptr<MongoTweetStorageIf> iface_;
};

class MongoTweetStorageNull : virtual public MongoTweetStorageIf {
 public:
  virtual ~MongoTweetStorageNull() {}
  void ping() {
    return;
  }
  void store_tweet(const Tweet& /* tweet */, const std::string& /* req_id */) {
    return;
  }
  void get_tweet(std::string& /* _return */, const std::string& /* user_id */, const std::string& /* unique_id */, const std::string& /* req_id */) {
    return;
  }
};


class MongoTweetStorage_ping_args {
 public:

  MongoTweetStorage_ping_args(const MongoTweetStorage_ping_args&);
  MongoTweetStorage_ping_args& operator=(const MongoTweetStorage_ping_args&);
  MongoTweetStorage_ping_args() {
  }

  virtual ~MongoTweetStorage_ping_args() throw();

  bool operator == (const MongoTweetStorage_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MongoTweetStorage_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MongoTweetStorage_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MongoTweetStorage_ping_pargs {
 public:


  virtual ~MongoTweetStorage_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MongoTweetStorage_ping_result {
 public:

  MongoTweetStorage_ping_result(const MongoTweetStorage_ping_result&);
  MongoTweetStorage_ping_result& operator=(const MongoTweetStorage_ping_result&);
  MongoTweetStorage_ping_result() {
  }

  virtual ~MongoTweetStorage_ping_result() throw();

  bool operator == (const MongoTweetStorage_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MongoTweetStorage_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MongoTweetStorage_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MongoTweetStorage_ping_presult {
 public:


  virtual ~MongoTweetStorage_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MongoTweetStorage_store_tweet_args__isset {
  _MongoTweetStorage_store_tweet_args__isset() : tweet(false), req_id(false) {}
  bool tweet :1;
  bool req_id :1;
} _MongoTweetStorage_store_tweet_args__isset;

class MongoTweetStorage_store_tweet_args {
 public:

  MongoTweetStorage_store_tweet_args(const MongoTweetStorage_store_tweet_args&);
  MongoTweetStorage_store_tweet_args& operator=(const MongoTweetStorage_store_tweet_args&);
  MongoTweetStorage_store_tweet_args() : req_id() {
  }

  virtual ~MongoTweetStorage_store_tweet_args() throw();
  Tweet tweet;
  std::string req_id;

  _MongoTweetStorage_store_tweet_args__isset __isset;

  void __set_tweet(const Tweet& val);

  void __set_req_id(const std::string& val);

  bool operator == (const MongoTweetStorage_store_tweet_args & rhs) const
  {
    if (!(tweet == rhs.tweet))
      return false;
    if (!(req_id == rhs.req_id))
      return false;
    return true;
  }
  bool operator != (const MongoTweetStorage_store_tweet_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MongoTweetStorage_store_tweet_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MongoTweetStorage_store_tweet_pargs {
 public:


  virtual ~MongoTweetStorage_store_tweet_pargs() throw();
  const Tweet* tweet;
  const std::string* req_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MongoTweetStorage_get_tweet_args__isset {
  _MongoTweetStorage_get_tweet_args__isset() : user_id(false), unique_id(false), req_id(false) {}
  bool user_id :1;
  bool unique_id :1;
  bool req_id :1;
} _MongoTweetStorage_get_tweet_args__isset;

class MongoTweetStorage_get_tweet_args {
 public:

  MongoTweetStorage_get_tweet_args(const MongoTweetStorage_get_tweet_args&);
  MongoTweetStorage_get_tweet_args& operator=(const MongoTweetStorage_get_tweet_args&);
  MongoTweetStorage_get_tweet_args() : user_id(), unique_id(), req_id() {
  }

  virtual ~MongoTweetStorage_get_tweet_args() throw();
  std::string user_id;
  std::string unique_id;
  std::string req_id;

  _MongoTweetStorage_get_tweet_args__isset __isset;

  void __set_user_id(const std::string& val);

  void __set_unique_id(const std::string& val);

  void __set_req_id(const std::string& val);

  bool operator == (const MongoTweetStorage_get_tweet_args & rhs) const
  {
    if (!(user_id == rhs.user_id))
      return false;
    if (!(unique_id == rhs.unique_id))
      return false;
    if (!(req_id == rhs.req_id))
      return false;
    return true;
  }
  bool operator != (const MongoTweetStorage_get_tweet_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MongoTweetStorage_get_tweet_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MongoTweetStorage_get_tweet_pargs {
 public:


  virtual ~MongoTweetStorage_get_tweet_pargs() throw();
  const std::string* user_id;
  const std::string* unique_id;
  const std::string* req_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MongoTweetStorage_get_tweet_result__isset {
  _MongoTweetStorage_get_tweet_result__isset() : success(false) {}
  bool success :1;
} _MongoTweetStorage_get_tweet_result__isset;

class MongoTweetStorage_get_tweet_result {
 public:

  MongoTweetStorage_get_tweet_result(const MongoTweetStorage_get_tweet_result&);
  MongoTweetStorage_get_tweet_result& operator=(const MongoTweetStorage_get_tweet_result&);
  MongoTweetStorage_get_tweet_result() : success() {
  }

  virtual ~MongoTweetStorage_get_tweet_result() throw();
  std::string success;

  _MongoTweetStorage_get_tweet_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const MongoTweetStorage_get_tweet_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MongoTweetStorage_get_tweet_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MongoTweetStorage_get_tweet_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MongoTweetStorage_get_tweet_presult__isset {
  _MongoTweetStorage_get_tweet_presult__isset() : success(false) {}
  bool success :1;
} _MongoTweetStorage_get_tweet_presult__isset;

class MongoTweetStorage_get_tweet_presult {
 public:


  virtual ~MongoTweetStorage_get_tweet_presult() throw();
  std::string* success;

  _MongoTweetStorage_get_tweet_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MongoTweetStorageClient : virtual public MongoTweetStorageIf {
 public:
  MongoTweetStorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MongoTweetStorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void store_tweet(const Tweet& tweet, const std::string& req_id);
  void send_store_tweet(const Tweet& tweet, const std::string& req_id);
  void get_tweet(std::string& _return, const std::string& user_id, const std::string& unique_id, const std::string& req_id);
  void send_get_tweet(const std::string& user_id, const std::string& unique_id, const std::string& req_id);
  void recv_get_tweet(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MongoTweetStorageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MongoTweetStorageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MongoTweetStorageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_store_tweet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_tweet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MongoTweetStorageProcessor(boost::shared_ptr<MongoTweetStorageIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &MongoTweetStorageProcessor::process_ping;
    processMap_["store_tweet"] = &MongoTweetStorageProcessor::process_store_tweet;
    processMap_["get_tweet"] = &MongoTweetStorageProcessor::process_get_tweet;
  }

  virtual ~MongoTweetStorageProcessor() {}
};

class MongoTweetStorageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MongoTweetStorageProcessorFactory(const ::boost::shared_ptr< MongoTweetStorageIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MongoTweetStorageIfFactory > handlerFactory_;
};

class MongoTweetStorageMultiface : virtual public MongoTweetStorageIf {
 public:
  MongoTweetStorageMultiface(std::vector<boost::shared_ptr<MongoTweetStorageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MongoTweetStorageMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MongoTweetStorageIf> > ifaces_;
  MongoTweetStorageMultiface() {}
  void add(boost::shared_ptr<MongoTweetStorageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void store_tweet(const Tweet& tweet, const std::string& req_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->store_tweet(tweet, req_id);
    }
    ifaces_[i]->store_tweet(tweet, req_id);
  }

  void get_tweet(std::string& _return, const std::string& user_id, const std::string& unique_id, const std::string& req_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_tweet(_return, user_id, unique_id, req_id);
    }
    ifaces_[i]->get_tweet(_return, user_id, unique_id, req_id);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MongoTweetStorageConcurrentClient : virtual public MongoTweetStorageIf {
 public:
  MongoTweetStorageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MongoTweetStorageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void store_tweet(const Tweet& tweet, const std::string& req_id);
  void send_store_tweet(const Tweet& tweet, const std::string& req_id);
  void get_tweet(std::string& _return, const std::string& user_id, const std::string& unique_id, const std::string& req_id);
  int32_t send_get_tweet(const std::string& user_id, const std::string& unique_id, const std::string& req_id);
  void recv_get_tweet(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
