/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MovieReviewDB_H
#define MovieReviewDB_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "NetflixMicroservices_types.h"

namespace NetflixMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MovieReviewDBIf {
 public:
  virtual ~MovieReviewDBIf() {}
  virtual void ping() = 0;
  virtual void write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating) = 0;
  virtual void get_movie_review(std::string& _return, const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num) = 0;
};

class MovieReviewDBIfFactory {
 public:
  typedef MovieReviewDBIf Handler;

  virtual ~MovieReviewDBIfFactory() {}

  virtual MovieReviewDBIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MovieReviewDBIf* /* handler */) = 0;
};

class MovieReviewDBIfSingletonFactory : virtual public MovieReviewDBIfFactory {
 public:
  MovieReviewDBIfSingletonFactory(const boost::shared_ptr<MovieReviewDBIf>& iface) : iface_(iface) {}
  virtual ~MovieReviewDBIfSingletonFactory() {}

  virtual MovieReviewDBIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MovieReviewDBIf* /* handler */) {}

 protected:
  boost::shared_ptr<MovieReviewDBIf> iface_;
};

class MovieReviewDBNull : virtual public MovieReviewDBIf {
 public:
  virtual ~MovieReviewDBNull() {}
  void ping() {
    return;
  }
  void write_movie_review(const std::string& /* req_id */, const std::string& /* movie_id */, const std::string& /* user_id */, const std::string& /* unique_id */, const std::string& /* rating */) {
    return;
  }
  void get_movie_review(std::string& /* _return */, const std::string& /* req_id */, const std::string& /* movie_id */, const int32_t /* begin_no */, const int32_t /* num */) {
    return;
  }
};


class MovieReviewDB_ping_args {
 public:

  MovieReviewDB_ping_args(const MovieReviewDB_ping_args&);
  MovieReviewDB_ping_args& operator=(const MovieReviewDB_ping_args&);
  MovieReviewDB_ping_args() {
  }

  virtual ~MovieReviewDB_ping_args() throw();

  bool operator == (const MovieReviewDB_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MovieReviewDB_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MovieReviewDB_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MovieReviewDB_ping_pargs {
 public:


  virtual ~MovieReviewDB_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MovieReviewDB_ping_result {
 public:

  MovieReviewDB_ping_result(const MovieReviewDB_ping_result&);
  MovieReviewDB_ping_result& operator=(const MovieReviewDB_ping_result&);
  MovieReviewDB_ping_result() {
  }

  virtual ~MovieReviewDB_ping_result() throw();

  bool operator == (const MovieReviewDB_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const MovieReviewDB_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MovieReviewDB_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MovieReviewDB_ping_presult {
 public:


  virtual ~MovieReviewDB_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MovieReviewDB_write_movie_review_args__isset {
  _MovieReviewDB_write_movie_review_args__isset() : req_id(false), movie_id(false), user_id(false), unique_id(false), rating(false) {}
  bool req_id :1;
  bool movie_id :1;
  bool user_id :1;
  bool unique_id :1;
  bool rating :1;
} _MovieReviewDB_write_movie_review_args__isset;

class MovieReviewDB_write_movie_review_args {
 public:

  MovieReviewDB_write_movie_review_args(const MovieReviewDB_write_movie_review_args&);
  MovieReviewDB_write_movie_review_args& operator=(const MovieReviewDB_write_movie_review_args&);
  MovieReviewDB_write_movie_review_args() : req_id(), movie_id(), user_id(), unique_id(), rating() {
  }

  virtual ~MovieReviewDB_write_movie_review_args() throw();
  std::string req_id;
  std::string movie_id;
  std::string user_id;
  std::string unique_id;
  std::string rating;

  _MovieReviewDB_write_movie_review_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_movie_id(const std::string& val);

  void __set_user_id(const std::string& val);

  void __set_unique_id(const std::string& val);

  void __set_rating(const std::string& val);

  bool operator == (const MovieReviewDB_write_movie_review_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(movie_id == rhs.movie_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(unique_id == rhs.unique_id))
      return false;
    if (!(rating == rhs.rating))
      return false;
    return true;
  }
  bool operator != (const MovieReviewDB_write_movie_review_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MovieReviewDB_write_movie_review_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MovieReviewDB_write_movie_review_pargs {
 public:


  virtual ~MovieReviewDB_write_movie_review_pargs() throw();
  const std::string* req_id;
  const std::string* movie_id;
  const std::string* user_id;
  const std::string* unique_id;
  const std::string* rating;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MovieReviewDB_get_movie_review_args__isset {
  _MovieReviewDB_get_movie_review_args__isset() : req_id(false), movie_id(false), begin_no(false), num(false) {}
  bool req_id :1;
  bool movie_id :1;
  bool begin_no :1;
  bool num :1;
} _MovieReviewDB_get_movie_review_args__isset;

class MovieReviewDB_get_movie_review_args {
 public:

  MovieReviewDB_get_movie_review_args(const MovieReviewDB_get_movie_review_args&);
  MovieReviewDB_get_movie_review_args& operator=(const MovieReviewDB_get_movie_review_args&);
  MovieReviewDB_get_movie_review_args() : req_id(), movie_id(), begin_no(0), num(0) {
  }

  virtual ~MovieReviewDB_get_movie_review_args() throw();
  std::string req_id;
  std::string movie_id;
  int32_t begin_no;
  int32_t num;

  _MovieReviewDB_get_movie_review_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_movie_id(const std::string& val);

  void __set_begin_no(const int32_t val);

  void __set_num(const int32_t val);

  bool operator == (const MovieReviewDB_get_movie_review_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(movie_id == rhs.movie_id))
      return false;
    if (!(begin_no == rhs.begin_no))
      return false;
    if (!(num == rhs.num))
      return false;
    return true;
  }
  bool operator != (const MovieReviewDB_get_movie_review_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MovieReviewDB_get_movie_review_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MovieReviewDB_get_movie_review_pargs {
 public:


  virtual ~MovieReviewDB_get_movie_review_pargs() throw();
  const std::string* req_id;
  const std::string* movie_id;
  const int32_t* begin_no;
  const int32_t* num;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MovieReviewDB_get_movie_review_result__isset {
  _MovieReviewDB_get_movie_review_result__isset() : success(false) {}
  bool success :1;
} _MovieReviewDB_get_movie_review_result__isset;

class MovieReviewDB_get_movie_review_result {
 public:

  MovieReviewDB_get_movie_review_result(const MovieReviewDB_get_movie_review_result&);
  MovieReviewDB_get_movie_review_result& operator=(const MovieReviewDB_get_movie_review_result&);
  MovieReviewDB_get_movie_review_result() : success() {
  }

  virtual ~MovieReviewDB_get_movie_review_result() throw();
  std::string success;

  _MovieReviewDB_get_movie_review_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const MovieReviewDB_get_movie_review_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MovieReviewDB_get_movie_review_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MovieReviewDB_get_movie_review_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MovieReviewDB_get_movie_review_presult__isset {
  _MovieReviewDB_get_movie_review_presult__isset() : success(false) {}
  bool success :1;
} _MovieReviewDB_get_movie_review_presult__isset;

class MovieReviewDB_get_movie_review_presult {
 public:


  virtual ~MovieReviewDB_get_movie_review_presult() throw();
  std::string* success;

  _MovieReviewDB_get_movie_review_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MovieReviewDBClient : virtual public MovieReviewDBIf {
 public:
  MovieReviewDBClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MovieReviewDBClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating);
  void send_write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating);
  void get_movie_review(std::string& _return, const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num);
  void send_get_movie_review(const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num);
  void recv_get_movie_review(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MovieReviewDBProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MovieReviewDBIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MovieReviewDBProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_write_movie_review(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_get_movie_review(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MovieReviewDBProcessor(boost::shared_ptr<MovieReviewDBIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &MovieReviewDBProcessor::process_ping;
    processMap_["write_movie_review"] = &MovieReviewDBProcessor::process_write_movie_review;
    processMap_["get_movie_review"] = &MovieReviewDBProcessor::process_get_movie_review;
  }

  virtual ~MovieReviewDBProcessor() {}
};

class MovieReviewDBProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MovieReviewDBProcessorFactory(const ::boost::shared_ptr< MovieReviewDBIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MovieReviewDBIfFactory > handlerFactory_;
};

class MovieReviewDBMultiface : virtual public MovieReviewDBIf {
 public:
  MovieReviewDBMultiface(std::vector<boost::shared_ptr<MovieReviewDBIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MovieReviewDBMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MovieReviewDBIf> > ifaces_;
  MovieReviewDBMultiface() {}
  void add(boost::shared_ptr<MovieReviewDBIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->write_movie_review(req_id, movie_id, user_id, unique_id, rating);
    }
    ifaces_[i]->write_movie_review(req_id, movie_id, user_id, unique_id, rating);
  }

  void get_movie_review(std::string& _return, const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->get_movie_review(_return, req_id, movie_id, begin_no, num);
    }
    ifaces_[i]->get_movie_review(_return, req_id, movie_id, begin_no, num);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MovieReviewDBConcurrentClient : virtual public MovieReviewDBIf {
 public:
  MovieReviewDBConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MovieReviewDBConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating);
  void send_write_movie_review(const std::string& req_id, const std::string& movie_id, const std::string& user_id, const std::string& unique_id, const std::string& rating);
  void get_movie_review(std::string& _return, const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num);
  int32_t send_get_movie_review(const std::string& req_id, const std::string& movie_id, const int32_t begin_no, const int32_t num);
  void recv_get_movie_review(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
