/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NetflixMicroservices_CONSTANTS_H
#define NetflixMicroservices_CONSTANTS_H

#include "NetflixMicroservices_types.h"

namespace NetflixMicroservices {

class NetflixMicroservicesConstants {
 public:
  NetflixMicroservicesConstants();

};

extern const NetflixMicroservicesConstants g_NetflixMicroservices_constants;

} // namespace

#endif
