/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProcessText_H
#define ProcessText_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "TwitterMicroservices_types.h"

namespace TwitterMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProcessTextIf {
 public:
  virtual ~ProcessTextIf() {}
  virtual void ping() = 0;
  virtual void process_text(const std::string& req_id, const std::string& text_data, const std::string& type) = 0;
};

class ProcessTextIfFactory {
 public:
  typedef ProcessTextIf Handler;

  virtual ~ProcessTextIfFactory() {}

  virtual ProcessTextIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProcessTextIf* /* handler */) = 0;
};

class ProcessTextIfSingletonFactory : virtual public ProcessTextIfFactory {
 public:
  ProcessTextIfSingletonFactory(const boost::shared_ptr<ProcessTextIf>& iface) : iface_(iface) {}
  virtual ~ProcessTextIfSingletonFactory() {}

  virtual ProcessTextIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProcessTextIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProcessTextIf> iface_;
};

class ProcessTextNull : virtual public ProcessTextIf {
 public:
  virtual ~ProcessTextNull() {}
  void ping() {
    return;
  }
  void process_text(const std::string& /* req_id */, const std::string& /* text_data */, const std::string& /* type */) {
    return;
  }
};


class ProcessText_ping_args {
 public:

  ProcessText_ping_args(const ProcessText_ping_args&);
  ProcessText_ping_args& operator=(const ProcessText_ping_args&);
  ProcessText_ping_args() {
  }

  virtual ~ProcessText_ping_args() throw();

  bool operator == (const ProcessText_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ProcessText_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessText_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessText_ping_pargs {
 public:


  virtual ~ProcessText_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessText_ping_result {
 public:

  ProcessText_ping_result(const ProcessText_ping_result&);
  ProcessText_ping_result& operator=(const ProcessText_ping_result&);
  ProcessText_ping_result() {
  }

  virtual ~ProcessText_ping_result() throw();

  bool operator == (const ProcessText_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ProcessText_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessText_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessText_ping_presult {
 public:


  virtual ~ProcessText_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProcessText_process_text_args__isset {
  _ProcessText_process_text_args__isset() : req_id(false), text_data(false), type(false) {}
  bool req_id :1;
  bool text_data :1;
  bool type :1;
} _ProcessText_process_text_args__isset;

class ProcessText_process_text_args {
 public:

  ProcessText_process_text_args(const ProcessText_process_text_args&);
  ProcessText_process_text_args& operator=(const ProcessText_process_text_args&);
  ProcessText_process_text_args() : req_id(), text_data(), type() {
  }

  virtual ~ProcessText_process_text_args() throw();
  std::string req_id;
  std::string text_data;
  std::string type;

  _ProcessText_process_text_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_text_data(const std::string& val);

  void __set_type(const std::string& val);

  bool operator == (const ProcessText_process_text_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(text_data == rhs.text_data))
      return false;
    if (!(type == rhs.type))
      return false;
    return true;
  }
  bool operator != (const ProcessText_process_text_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessText_process_text_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessText_process_text_pargs {
 public:


  virtual ~ProcessText_process_text_pargs() throw();
  const std::string* req_id;
  const std::string* text_data;
  const std::string* type;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ProcessTextClient : virtual public ProcessTextIf {
 public:
  ProcessTextClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProcessTextClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void process_text(const std::string& req_id, const std::string& text_data, const std::string& type);
  void send_process_text(const std::string& req_id, const std::string& text_data, const std::string& type);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProcessTextProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProcessTextIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProcessTextProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_process_text(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProcessTextProcessor(boost::shared_ptr<ProcessTextIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &ProcessTextProcessor::process_ping;
    processMap_["process_text"] = &ProcessTextProcessor::process_process_text;
  }

  virtual ~ProcessTextProcessor() {}
};

class ProcessTextProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProcessTextProcessorFactory(const ::boost::shared_ptr< ProcessTextIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProcessTextIfFactory > handlerFactory_;
};

class ProcessTextMultiface : virtual public ProcessTextIf {
 public:
  ProcessTextMultiface(std::vector<boost::shared_ptr<ProcessTextIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProcessTextMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProcessTextIf> > ifaces_;
  ProcessTextMultiface() {}
  void add(boost::shared_ptr<ProcessTextIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void process_text(const std::string& req_id, const std::string& text_data, const std::string& type) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->process_text(req_id, text_data, type);
    }
    ifaces_[i]->process_text(req_id, text_data, type);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProcessTextConcurrentClient : virtual public ProcessTextIf {
 public:
  ProcessTextConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProcessTextConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void process_text(const std::string& req_id, const std::string& text_data, const std::string& type);
  void send_process_text(const std::string& req_id, const std::string& text_data, const std::string& type);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
