/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ProcessTag_H
#define ProcessTag_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "TwitterMicroservices_types.h"

namespace TwitterMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ProcessTagIf {
 public:
  virtual ~ProcessTagIf() {}
  virtual void ping() = 0;
  virtual void process_tag(const std::string& req_id, const std::string& text_data, const std::string& type) = 0;
};

class ProcessTagIfFactory {
 public:
  typedef ProcessTagIf Handler;

  virtual ~ProcessTagIfFactory() {}

  virtual ProcessTagIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ProcessTagIf* /* handler */) = 0;
};

class ProcessTagIfSingletonFactory : virtual public ProcessTagIfFactory {
 public:
  ProcessTagIfSingletonFactory(const boost::shared_ptr<ProcessTagIf>& iface) : iface_(iface) {}
  virtual ~ProcessTagIfSingletonFactory() {}

  virtual ProcessTagIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ProcessTagIf* /* handler */) {}

 protected:
  boost::shared_ptr<ProcessTagIf> iface_;
};

class ProcessTagNull : virtual public ProcessTagIf {
 public:
  virtual ~ProcessTagNull() {}
  void ping() {
    return;
  }
  void process_tag(const std::string& /* req_id */, const std::string& /* text_data */, const std::string& /* type */) {
    return;
  }
};


class ProcessTag_ping_args {
 public:

  ProcessTag_ping_args(const ProcessTag_ping_args&);
  ProcessTag_ping_args& operator=(const ProcessTag_ping_args&);
  ProcessTag_ping_args() {
  }

  virtual ~ProcessTag_ping_args() throw();

  bool operator == (const ProcessTag_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ProcessTag_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessTag_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessTag_ping_pargs {
 public:


  virtual ~ProcessTag_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessTag_ping_result {
 public:

  ProcessTag_ping_result(const ProcessTag_ping_result&);
  ProcessTag_ping_result& operator=(const ProcessTag_ping_result&);
  ProcessTag_ping_result() {
  }

  virtual ~ProcessTag_ping_result() throw();

  bool operator == (const ProcessTag_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ProcessTag_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessTag_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessTag_ping_presult {
 public:


  virtual ~ProcessTag_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ProcessTag_process_tag_args__isset {
  _ProcessTag_process_tag_args__isset() : req_id(false), text_data(false), type(false) {}
  bool req_id :1;
  bool text_data :1;
  bool type :1;
} _ProcessTag_process_tag_args__isset;

class ProcessTag_process_tag_args {
 public:

  ProcessTag_process_tag_args(const ProcessTag_process_tag_args&);
  ProcessTag_process_tag_args& operator=(const ProcessTag_process_tag_args&);
  ProcessTag_process_tag_args() : req_id(), text_data(), type() {
  }

  virtual ~ProcessTag_process_tag_args() throw();
  std::string req_id;
  std::string text_data;
  std::string type;

  _ProcessTag_process_tag_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_text_data(const std::string& val);

  void __set_type(const std::string& val);

  bool operator == (const ProcessTag_process_tag_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(text_data == rhs.text_data))
      return false;
    if (!(type == rhs.type))
      return false;
    return true;
  }
  bool operator != (const ProcessTag_process_tag_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProcessTag_process_tag_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ProcessTag_process_tag_pargs {
 public:


  virtual ~ProcessTag_process_tag_pargs() throw();
  const std::string* req_id;
  const std::string* text_data;
  const std::string* type;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ProcessTagClient : virtual public ProcessTagIf {
 public:
  ProcessTagClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProcessTagClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void process_tag(const std::string& req_id, const std::string& text_data, const std::string& type);
  void send_process_tag(const std::string& req_id, const std::string& text_data, const std::string& type);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ProcessTagProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ProcessTagIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ProcessTagProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_process_tag(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ProcessTagProcessor(boost::shared_ptr<ProcessTagIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &ProcessTagProcessor::process_ping;
    processMap_["process_tag"] = &ProcessTagProcessor::process_process_tag;
  }

  virtual ~ProcessTagProcessor() {}
};

class ProcessTagProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ProcessTagProcessorFactory(const ::boost::shared_ptr< ProcessTagIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ProcessTagIfFactory > handlerFactory_;
};

class ProcessTagMultiface : virtual public ProcessTagIf {
 public:
  ProcessTagMultiface(std::vector<boost::shared_ptr<ProcessTagIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ProcessTagMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ProcessTagIf> > ifaces_;
  ProcessTagMultiface() {}
  void add(boost::shared_ptr<ProcessTagIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void process_tag(const std::string& req_id, const std::string& text_data, const std::string& type) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->process_tag(req_id, text_data, type);
    }
    ifaces_[i]->process_tag(req_id, text_data, type);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ProcessTagConcurrentClient : virtual public ProcessTagIf {
 public:
  ProcessTagConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ProcessTagConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void process_tag(const std::string& req_id, const std::string& text_data, const std::string& type);
  void send_process_tag(const std::string& req_id, const std::string& text_data, const std::string& type);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
