/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ReviewStorage_H
#define ReviewStorage_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "NetflixMicroservices_types.h"

namespace NetflixMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ReviewStorageIf {
 public:
  virtual ~ReviewStorageIf() {}
  virtual void ping() = 0;
  virtual void review_storage(const std::string& req_id, const Review& review) = 0;
};

class ReviewStorageIfFactory {
 public:
  typedef ReviewStorageIf Handler;

  virtual ~ReviewStorageIfFactory() {}

  virtual ReviewStorageIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ReviewStorageIf* /* handler */) = 0;
};

class ReviewStorageIfSingletonFactory : virtual public ReviewStorageIfFactory {
 public:
  ReviewStorageIfSingletonFactory(const boost::shared_ptr<ReviewStorageIf>& iface) : iface_(iface) {}
  virtual ~ReviewStorageIfSingletonFactory() {}

  virtual ReviewStorageIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ReviewStorageIf* /* handler */) {}

 protected:
  boost::shared_ptr<ReviewStorageIf> iface_;
};

class ReviewStorageNull : virtual public ReviewStorageIf {
 public:
  virtual ~ReviewStorageNull() {}
  void ping() {
    return;
  }
  void review_storage(const std::string& /* req_id */, const Review& /* review */) {
    return;
  }
};


class ReviewStorage_ping_args {
 public:

  ReviewStorage_ping_args(const ReviewStorage_ping_args&);
  ReviewStorage_ping_args& operator=(const ReviewStorage_ping_args&);
  ReviewStorage_ping_args() {
  }

  virtual ~ReviewStorage_ping_args() throw();

  bool operator == (const ReviewStorage_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ReviewStorage_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReviewStorage_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ReviewStorage_ping_pargs {
 public:


  virtual ~ReviewStorage_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ReviewStorage_ping_result {
 public:

  ReviewStorage_ping_result(const ReviewStorage_ping_result&);
  ReviewStorage_ping_result& operator=(const ReviewStorage_ping_result&);
  ReviewStorage_ping_result() {
  }

  virtual ~ReviewStorage_ping_result() throw();

  bool operator == (const ReviewStorage_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ReviewStorage_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReviewStorage_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ReviewStorage_ping_presult {
 public:


  virtual ~ReviewStorage_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ReviewStorage_review_storage_args__isset {
  _ReviewStorage_review_storage_args__isset() : req_id(false), review(false) {}
  bool req_id :1;
  bool review :1;
} _ReviewStorage_review_storage_args__isset;

class ReviewStorage_review_storage_args {
 public:

  ReviewStorage_review_storage_args(const ReviewStorage_review_storage_args&);
  ReviewStorage_review_storage_args& operator=(const ReviewStorage_review_storage_args&);
  ReviewStorage_review_storage_args() : req_id() {
  }

  virtual ~ReviewStorage_review_storage_args() throw();
  std::string req_id;
  Review review;

  _ReviewStorage_review_storage_args__isset __isset;

  void __set_req_id(const std::string& val);

  void __set_review(const Review& val);

  bool operator == (const ReviewStorage_review_storage_args & rhs) const
  {
    if (!(req_id == rhs.req_id))
      return false;
    if (!(review == rhs.review))
      return false;
    return true;
  }
  bool operator != (const ReviewStorage_review_storage_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReviewStorage_review_storage_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ReviewStorage_review_storage_pargs {
 public:


  virtual ~ReviewStorage_review_storage_pargs() throw();
  const std::string* req_id;
  const Review* review;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ReviewStorageClient : virtual public ReviewStorageIf {
 public:
  ReviewStorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ReviewStorageClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void review_storage(const std::string& req_id, const Review& review);
  void send_review_storage(const std::string& req_id, const Review& review);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ReviewStorageProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ReviewStorageIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ReviewStorageProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_review_storage(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ReviewStorageProcessor(boost::shared_ptr<ReviewStorageIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &ReviewStorageProcessor::process_ping;
    processMap_["review_storage"] = &ReviewStorageProcessor::process_review_storage;
  }

  virtual ~ReviewStorageProcessor() {}
};

class ReviewStorageProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ReviewStorageProcessorFactory(const ::boost::shared_ptr< ReviewStorageIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ReviewStorageIfFactory > handlerFactory_;
};

class ReviewStorageMultiface : virtual public ReviewStorageIf {
 public:
  ReviewStorageMultiface(std::vector<boost::shared_ptr<ReviewStorageIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ReviewStorageMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ReviewStorageIf> > ifaces_;
  ReviewStorageMultiface() {}
  void add(boost::shared_ptr<ReviewStorageIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void review_storage(const std::string& req_id, const Review& review) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->review_storage(req_id, review);
    }
    ifaces_[i]->review_storage(req_id, review);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ReviewStorageConcurrentClient : virtual public ReviewStorageIf {
 public:
  ReviewStorageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ReviewStorageConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void review_storage(const std::string& req_id, const Review& review);
  void send_review_storage(const std::string& req_id, const Review& review);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
