// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ReviewStorage.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::NetflixMicroservices;

class ReviewStorageHandler : virtual public ReviewStorageIf {
 public:
  ReviewStorageHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void review_storage(const std::string& req_id, const Review& review) {
    // Your implementation goes here
    printf("review_storage\n");
  }

  void get_review(Review& _return, const std::string& req_id, const std::string& movie_id, const std::string& unique_id) {
    // Your implementation goes here
    printf("get_review\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ReviewStorageHandler> handler(new ReviewStorageHandler());
  shared_ptr<TProcessor> processor(new ReviewStorageProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

