/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TwitterMicroservices_CONSTANTS_H
#define TwitterMicroservices_CONSTANTS_H

#include "TwitterMicroservices_types.h"

namespace TwitterMicroservices {

class TwitterMicroservicesConstants {
 public:
  TwitterMicroservicesConstants();

};

extern const TwitterMicroservicesConstants g_TwitterMicroservices_constants;

} // namespace

#endif
