/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WriteFavorite_H
#define WriteFavorite_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "TwitterMicroservices_types.h"

namespace TwitterMicroservices {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class WriteFavoriteIf {
 public:
  virtual ~WriteFavoriteIf() {}
  virtual void ping() = 0;
  virtual void write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id) = 0;
};

class WriteFavoriteIfFactory {
 public:
  typedef WriteFavoriteIf Handler;

  virtual ~WriteFavoriteIfFactory() {}

  virtual WriteFavoriteIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(WriteFavoriteIf* /* handler */) = 0;
};

class WriteFavoriteIfSingletonFactory : virtual public WriteFavoriteIfFactory {
 public:
  WriteFavoriteIfSingletonFactory(const boost::shared_ptr<WriteFavoriteIf>& iface) : iface_(iface) {}
  virtual ~WriteFavoriteIfSingletonFactory() {}

  virtual WriteFavoriteIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(WriteFavoriteIf* /* handler */) {}

 protected:
  boost::shared_ptr<WriteFavoriteIf> iface_;
};

class WriteFavoriteNull : virtual public WriteFavoriteIf {
 public:
  virtual ~WriteFavoriteNull() {}
  void ping() {
    return;
  }
  void write_favorite(const std::string& /* user_id */, const std::string& /* unique_id */, const std::string& /* author_id */, const std::string& /* req_id */) {
    return;
  }
};


class WriteFavorite_ping_args {
 public:

  WriteFavorite_ping_args(const WriteFavorite_ping_args&);
  WriteFavorite_ping_args& operator=(const WriteFavorite_ping_args&);
  WriteFavorite_ping_args() {
  }

  virtual ~WriteFavorite_ping_args() throw();

  bool operator == (const WriteFavorite_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WriteFavorite_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WriteFavorite_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WriteFavorite_ping_pargs {
 public:


  virtual ~WriteFavorite_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WriteFavorite_ping_result {
 public:

  WriteFavorite_ping_result(const WriteFavorite_ping_result&);
  WriteFavorite_ping_result& operator=(const WriteFavorite_ping_result&);
  WriteFavorite_ping_result() {
  }

  virtual ~WriteFavorite_ping_result() throw();

  bool operator == (const WriteFavorite_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WriteFavorite_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WriteFavorite_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WriteFavorite_ping_presult {
 public:


  virtual ~WriteFavorite_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _WriteFavorite_write_favorite_args__isset {
  _WriteFavorite_write_favorite_args__isset() : user_id(false), unique_id(false), author_id(false), req_id(false) {}
  bool user_id :1;
  bool unique_id :1;
  bool author_id :1;
  bool req_id :1;
} _WriteFavorite_write_favorite_args__isset;

class WriteFavorite_write_favorite_args {
 public:

  WriteFavorite_write_favorite_args(const WriteFavorite_write_favorite_args&);
  WriteFavorite_write_favorite_args& operator=(const WriteFavorite_write_favorite_args&);
  WriteFavorite_write_favorite_args() : user_id(), unique_id(), author_id(), req_id() {
  }

  virtual ~WriteFavorite_write_favorite_args() throw();
  std::string user_id;
  std::string unique_id;
  std::string author_id;
  std::string req_id;

  _WriteFavorite_write_favorite_args__isset __isset;

  void __set_user_id(const std::string& val);

  void __set_unique_id(const std::string& val);

  void __set_author_id(const std::string& val);

  void __set_req_id(const std::string& val);

  bool operator == (const WriteFavorite_write_favorite_args & rhs) const
  {
    if (!(user_id == rhs.user_id))
      return false;
    if (!(unique_id == rhs.unique_id))
      return false;
    if (!(author_id == rhs.author_id))
      return false;
    if (!(req_id == rhs.req_id))
      return false;
    return true;
  }
  bool operator != (const WriteFavorite_write_favorite_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WriteFavorite_write_favorite_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WriteFavorite_write_favorite_pargs {
 public:


  virtual ~WriteFavorite_write_favorite_pargs() throw();
  const std::string* user_id;
  const std::string* unique_id;
  const std::string* author_id;
  const std::string* req_id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class WriteFavoriteClient : virtual public WriteFavoriteIf {
 public:
  WriteFavoriteClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WriteFavoriteClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id);
  void send_write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class WriteFavoriteProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<WriteFavoriteIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (WriteFavoriteProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_write_favorite(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  WriteFavoriteProcessor(boost::shared_ptr<WriteFavoriteIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &WriteFavoriteProcessor::process_ping;
    processMap_["write_favorite"] = &WriteFavoriteProcessor::process_write_favorite;
  }

  virtual ~WriteFavoriteProcessor() {}
};

class WriteFavoriteProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  WriteFavoriteProcessorFactory(const ::boost::shared_ptr< WriteFavoriteIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< WriteFavoriteIfFactory > handlerFactory_;
};

class WriteFavoriteMultiface : virtual public WriteFavoriteIf {
 public:
  WriteFavoriteMultiface(std::vector<boost::shared_ptr<WriteFavoriteIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~WriteFavoriteMultiface() {}
 protected:
  std::vector<boost::shared_ptr<WriteFavoriteIf> > ifaces_;
  WriteFavoriteMultiface() {}
  void add(boost::shared_ptr<WriteFavoriteIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->write_favorite(user_id, unique_id, author_id, req_id);
    }
    ifaces_[i]->write_favorite(user_id, unique_id, author_id, req_id);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class WriteFavoriteConcurrentClient : virtual public WriteFavoriteIf {
 public:
  WriteFavoriteConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WriteFavoriteConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id);
  void send_write_favorite(const std::string& user_id, const std::string& unique_id, const std::string& author_id, const std::string& req_id);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
