// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WriteUserGraph.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::TwitterMicroservices;

class WriteUserGraphHandler : virtual public WriteUserGraphIf {
 public:
  WriteUserGraphHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void write_graph(const std::string& user_id, const std::string& unique_id, const std::string& req_id) {
    // Your implementation goes here
    printf("write_graph\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WriteUserGraphHandler> handler(new WriteUserGraphHandler());
  shared_ptr<TProcessor> processor(new WriteUserGraphProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

